#!/usr/bin/env zsh

arc=$(echo -e {GROW,COLLAPSE,DISCIPLINE,TRANSFORM}\ {1,2,3,4,5,6,7,8,9}{0,}{0,}\ years\ from\ now\\n | grep . | sort -R | head -n 1)
terrain=$(echo -e {EDUCATION,SECURITY,SOCIALISM,GRANDMA\'S\ HOUSE,OUTER\ SPACE,THE\ OCEAN,THE\ BEACH,HOTEL,PRISON,THE\ HOME,BACK\ YARD,THE\ PARK,THE\ WILDERNESS,A\ CAVERN,PUBLIC\ TRANSPORTATION,THE\ CITY,THE\ FARM,IN\ TRANSIT,ON\ VACATION,CAPITALISM,WAR,OCCUPIED\ TERRITORY,THE\ GROCERY\ STORE,THE\ OFFICE,ONLINE,IN\ PUBLIC,IN\ PRIVATE,THE\ BEDROOM,THE\ BATHROOM,UNDERGROUND,THE\ CLOUDS,THEOCRACY,MONARCHY,OLIGARCHY,KLEPTOCRACY,ANARCHY}\\n | grep . | sort -R | head -n 1)
object=$(echo -e {TUBE,TORUS,CUBE,RECTANGLE,RHOMBUS,STOOL,PYRAMID,TRIANGLE,CONE,LATTICE,BLOB,SPHERE,TREE,RHIZOME,WEB,CLUMP,CLUSTER,POSTCARD,WINDOW,COUCH,CAP,CYLINDER,MUSHROOM}\\n | grep . | sort -R | head -n 1)
mood=$(echo -e {DELIGHT,EXCITEMENT,AROUSAL,FEAR,ANGER,DISDAIN,DRIVE,INSPIRATION,BOREDOM,DROWSINESS,TORPOR,DESIRE,BUZZ,DEVOTION}\\n | grep . | sort -R | head -n 1)
echo -e "Arc:\t$arc\nTerrain:\t$terrain\nObject:\t$object\nMood:\t$mood"

